version: '3.8'

services:

  db:
    env_file:
      - .env
    image: postgres:13.0-alpine
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  backend:
    image: artemisfree/foodgram:latest
    # build: ../backend/
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/backend/staticfiles/
      - media_value:/app/backend/media/
    env_file:
      - ./.env

  frontend:
    image: artemisfree/foodgram_frontend:latest
    # build:
    #   context: ../frontend/
    #   dockerfile: Dockerfile
    depends_on:
      - backend
    # restart: always
    volumes:
      # - result_build:/app/result_build/build/
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/
      - ../frontend/build:/usr/share/nginx/html/
      # - result_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  # result_build:
  postgres_data:
  static_value:
  media_value:

  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ../frontend/:/app/result_build/
  # nginx:
  #   image: nginx:1.19.3
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ../frontend/build:/usr/share/nginx/html/
  #     - ../docs/:/usr/share/nginx/html/api/docs/