# Generated by Django 2.2.19 on 2022-05-22 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220511_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('slices', 'slices'), ('tablespoon', 'tablespoon'), ('teaspoon', 'teaspoon'), ('glass', 'glass'), ('pinch', 'pinch'), ('pieces', 'pieces'), ('ml', 'ml'), ('l', 'l'), ('to taste', 'to taste')], default='g', help_text='Выберете единицы измерения', max_length=200, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Укажите время приготовления', validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления - одна минута')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Выберите изображение рецепта', upload_to='v1/recipes/image/', verbose_name='Изображение'),
        ),
    ]
