# Generated by Django 2.2.19 on 2022-05-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220523_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Выберите изображение рецепта', upload_to='recipes/image/', verbose_name='Изображение'),
        ),
    ]
