# Generated by Django 2.2.19 on 2022-05-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscription',
            new_name='is_subscribed',
        ),
    ]
